name: Release Security Agent Policies

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Configure Git
        run: |
          git config user.name "$GITHUB_ACTOR"
          git config user.email "$GITHUB_ACTOR@users.noreply.github.com"

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - First Change
            - Second Change
          draft: false
          prerelease: false

      - name: Create Compliance Benchmarks ConfigMap
        uses: steebchen/kubectl@master
        with:
          args: create configmap datadog-compliance-benchmarks --dry-run -o yaml --from-file=./compliance/containers > ./datadog-compliance-benchmarks.yaml

      - name: Create Runtime Security Policies ConfigMap
        uses: steebchen/kubectl@master
        with:
          args: create configmap datadog-runtime-policies --dry-run -o yaml --from-file=./runtime > ./datadog-runtime-policies.yaml

      - name: Upload Compliance Benchmarks ConfigMap
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./datadog-compliance-benchmarks.yaml
          asset_name: datadog-compliance-benchmarks.yaml
          asset_content_type: application/yaml

      - name: Upload Runtime Security Policies ConfigMap
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./datadog-runtime-policies.yaml
          asset_name: datadog-runtime-policies.yaml
          asset_content_type: application/yaml