name: Release Security Agent Policies

on:
  push #:
    #    tags:
    #  - 'v*'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Create Compliance Benchmarks ConfigMap
        uses: steebchen/kubectl@v2.0.0
        with:
          command: create configmap datadog-compliance-benchmarks --dry-run -o yaml --from-file=./compliance/containers > ./datadog-compliance-benchmarks.yaml

      - name: Create Runtime Security Policies ConfigMap
        uses: steebchen/kubectl@v2.0.0
        with:
          command: create configmap datadog-runtime-policies --dry-run -o yaml --from-file=./runtime > ./datadog-runtime-policies.yaml

      - name: Create Release
        uses: softprops/action-gh-release@v1
        id: create_release
        with:
          name: Release ${{ github.ref }}
          body: |
            Changes in this Release
            - Updated compliance benchmarks and runtime security policies for Datadog Security Agent.
          draft: false
          prerelease: false
          files: |
            datadog-compliance-benchmarks.yaml
            datadog-runtime-policies.yaml
